### ISSUE TITLE
Club Application 

### ISSUE THREAD

**Issue by sunyu912** [cppignite/ignite-hq#1]
Prepare all the things need for the application.

Get everything ready by mid August.

**Comment by sunyu912** [comment]
@anthonygraca @mostafavahidi @dave-luk 

Let's get all the paperwork done THIS WEEK.

Could you please send me the form I need to do?

**Comment by mostafavahidi** [comment]
On my part, as a scheduler, I've already completed and submitted the Room Request form for the club meeting and it's pending for approval so far (As requested, I went with room 8-52 on Tuesdays at U-Hour). I also have to fill the Event Application form that requires @sunyu912 signature. I will print that out and have yu sun sign it tomorrow after class. However, that will take longer to complete because we have to get the signature of a bunch of other departments before we turn in the form.

**Comment by sunyu912** [comment]
Awesome! Thanks Mostafa. Just bring the form and I will sign it. That's why
we need to start this early. Let me know who else we need to talk and get
signatures.

**Comment by mostafavahidi** [comment]
@anthonygraca @dave-luk @sunyu912 Okay, so today I called the OSLCC office to ask about the event application and they said that before we submit any applications, we need to become a chartered club. So that is priority number 1. Also, after we become a chartered club (by completing blackboard course material and doing the quiz and such) and receiving the confirmation email. Then, we can submit the event application. They also said they will accept that beginning September 1st. I don't know if we already are classified as a chartered club or not but thought I should update you guys on my end.

**Comment by sunyu912** [comment]
@anthonygraca Any comments on this? Where are we on the application?
